---
title: '01'
documentclass: ctex
geometry: margin=2cm
output:
  html_document:
    toc: true
    df_print: paged
  rticles::ctex: null
  pdf_document:
    toc: true
---

## 导入数据

```{r out.width = '100%', message=FALSE, warning=FALSE}
library(tidyverse)
data <- data.frame(
  x1 = c(3.7,5.7,3.8,3.2,3.1,4.6,2.4,7.2,6.7,5.4,3.9,4.5,3.5,4.5,1.5,8.5,4.5,6.5,4.1,5.5),
  x2 = c(48.5,65.1,47.2,53.2,55.5,36.1,24.8,33.1,47.4,54.1,36.9,58.8,27.8,40.2,13.5,56.4,71.6,52.8,44.1,40.9),
  x3 = c(9.3,8.0,10.9,12.0,9.7,7.9,14.0,7.6,8.5,11.3,12.7,12.3,9.8,8.4,10.1,7.1,8.2,10.9,11.2,9.4)
)
data %>% head(5)
```

## 第(1)问

### 直接调用函数

```{r ,fig.showtext=TRUE, message=FALSE, warning=FALSE}
library(ICSNP)
mu0 <- c(4, 50, 10)
result <- HotellingsT2(data, mu=mu0)
print(result)
```

p值0.06493，不能拒绝原假设

### 手动计算

```{r,fig.showtext=TRUE, message=FALSE, warning=FALSE}
# 计算样本均值向量和协方差矩阵
x_ave = colMeans(data)
S <- cov(data) #协方差矩阵
S_inv <- solve(S) #逆矩阵
n <- nrow(data)  # 样本量 n = 20
p <- ncol(data)  # 变量维度 p = 3

F <- (n-p)*n/(p*(n-1)) * t(x_ave - mu0) %*% S_inv %*% (x_ave - mu0)

print(x_ave)
print(S)
print(S_inv)
print(F)
print(qf(0.95, 3, 17))
```

样本均值向量 $\overline{x}=(4.640,45.400,9.965)'$

协方差矩阵 $$
S=\left(\begin{array}{1}
2.879368 & 10.0100 & -1.809053 \\
10.010000 & 199.7884 & -5.640000 \\
-1.809053 & -5.6400 & 3.627658
\end{array}\right)
$$

协方差矩阵的逆

$$
S^{-1}=\left(\begin{array}{1}
0.58615531 & -0.022085719 & 0.257968742 \\
-0.02208572 & 0.006067227 & -0.001580929 \\
0.25796874 & -0.001580929 & 0.401846765
\end{array}\right)
$$

$F=\frac{(n-p)n}{p(n-1)}(\overline{x}-\mu_0)'S^{-1}(\overline{x}-\mu_0)=2.904546 < F_{0.005}(3,17)=3.196777$

接受$H_0$

## 第(2)问

$T^{2}_{0.05}(3,19)=10.729$

$$
20 \times \left(\begin{array}{1}
4.64-\mu_1 \\ 45.4-\mu_2 \\ 9.965-\mu_3
\end{array}\right)'
\left(\begin{array}{1}
0.58615531 & -0.022085719 & 0.257968742 \\
-0.02208572 & 0.006067227 & -0.001580929 \\
0.25796874 & -0.001580929 & 0.401846765
\end{array}\right)
\left(\begin{array}{1}
4.64-\mu_1 \\ 45.4-\mu_2 \\ 9.965-\mu_3
\end{array}\right)\leq 10.729
$$

绘图

```{r,out.width = '100%', message=FALSE, warning=FALSE}
library(rgl)
radius2 = 10.729
ellipsoid <- ellipse3d(S, centre = x_ave, t = sqrt(radius2))
plot3d(ellipsoid, col = "skyblue", alpha = 0.5)
points3d(x_ave[1], x_ave[2], x_ave[3], col = "black", size = 10)
points3d(data$x1, data$x2, data$x3, col = "red", size = 8)
```

## 第(3)问

$T_{0.05}(3,19)=3.276$
$\mu_i=\overline{x_i}\pm3.276 \times \sqrt{s_{ii}}/\sqrt{20}$
$$
\begin{array}{1}\mu_1 \in (3.397, 5.883) & \mu_2 \in (35.048, 55.753) & \mu_3 \in (8.57, 11.36)\end{array}
$$

计算邦弗伦尼
```{r,out.width = '100%', message=FALSE, warning=FALSE}
bonferroni_ci <- function(data, alpha = 0.05) {
  n <- nrow(data)
  p <- ncol(data)
  means <- colMeans(data)
  sds <- apply(data, 2, sd)
  t_crit <- qt(1 - alpha / (2 * p), df = n - 1)
  error <- t_crit * sds / sqrt(n)
  lower <- means - error
  upper <- means + error
  result <- data.frame(
    Variable = colnames(data),
    Mean = round(means, 3),
    Lower = round(lower, 3),
    Upper = round(upper, 3)
  )
  return(result)
}
bonferroni_ci(data, alpha = 0.05)

```

邦弗伦尼范围更小